### ISSUE TITLE
General Auth

### ISSUE THREAD

**Issue by mikeboan** [bdberm/recipes#72]
- [x] clear errors on form type change
- [x] after logging in: jQuery.Deferred exception: this.props.errors.map is not a function TypeError: this.props.errors.map is not a function
- [x] should stay logged in after refresh
- [x] form box seems taller than it needs to be?
- [x] errors shouldn't change the positioning of form inputs

**Comment by bdberm** [comment]
@mikeboan I'm not able to re-produce not being logged in after  refresh, can you let me know what youa r seeing indicating that?

**Comment by mikeboan** [comment]
on log in the header would disappear and then on refresh the header would reappear with the login button, but that doesn't seem to be happening anymore

**Comment by bdberm** [comment]
I think it may have just been because I had horrible red type on purple button so you couldn't see the change maybe, I changed text to white so may be more obvious now. Anyway, fair for me to go ahead and mark as done?

**Comment by mikeboan** [comment]
yeah, looks good to me

**Comment by mikeboan** [comment]
scratch that, it happened again

**Comment by bdberm** [comment]
gah, what was the series of clicks?

**Comment by bdberm** [comment]
ah seeing weirdness on Heroku now, disregard

**Comment by bdberm** [comment]
@mikeboan believe these are all fixed up (lost hours due to forgetting preventDefault on form submit...hopefully learned my lesson!)

LMK if it looks good to you and I'll close
